// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/sdk.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaprModuleKind int32

const (
	DaprModuleKind_DaprModuleKindUnknown    DaprModuleKind = 0
	DaprModuleKind_DaprModuleKindInvocation DaprModuleKind = 1
	DaprModuleKind_DaprModuleKindEvent      DaprModuleKind = 2
	DaprModuleKind_DaprModuleKindDelayEvent DaprModuleKind = 3
	DaprModuleKind_DaprModuleKindHealth     DaprModuleKind = 4
)

// Enum value maps for DaprModuleKind.
var (
	DaprModuleKind_name = map[int32]string{
		0: "DaprModuleKindUnknown",
		1: "DaprModuleKindInvocation",
		2: "DaprModuleKindEvent",
		3: "DaprModuleKindDelayEvent",
		4: "DaprModuleKindHealth",
	}
	DaprModuleKind_value = map[string]int32{
		"DaprModuleKindUnknown":    0,
		"DaprModuleKindInvocation": 1,
		"DaprModuleKindEvent":      2,
		"DaprModuleKindDelayEvent": 3,
		"DaprModuleKindHealth":     4,
	}
)

func (x DaprModuleKind) Enum() *DaprModuleKind {
	p := new(DaprModuleKind)
	*p = x
	return p
}

func (x DaprModuleKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DaprModuleKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sdk_proto_enumTypes[0].Descriptor()
}

func (DaprModuleKind) Type() protoreflect.EnumType {
	return &file_proto_sdk_proto_enumTypes[0]
}

func (x DaprModuleKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DaprModuleKind.Descriptor instead.
func (DaprModuleKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_sdk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sdk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 按limit分页
type ListParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`         // 页码
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParam) Reset() {
	*x = ListParam{}
	mi := &file_proto_sdk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParam) ProtoMessage() {}

func (x *ListParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sdk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParam.ProtoReflect.Descriptor instead.
func (*ListParam) Descriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *ListParam) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListParam) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DaprHandler struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleKind    DaprModuleKind         `protobuf:"varint,1,opt,name=moduleKind,proto3,enum=protobuf.DaprModuleKind" json:"moduleKind,omitempty"`                                               // 模块类型
	PkgPath       string                 `protobuf:"bytes,2,opt,name=pkgPath,proto3" json:"pkgPath,omitempty"`                                                                                   // 包路径
	Module        string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`                                                                                     // 模块名
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                                                                         // 处理函数名
	Alias         string                 `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`                                                                                       // 处理函数别名
	Annotations   map[string]string      `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 注解
	Comments      []string               `protobuf:"bytes,6,rep,name=comments,proto3" json:"comments,omitempty"`                                                                                 // 注释
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaprHandler) Reset() {
	*x = DaprHandler{}
	mi := &file_proto_sdk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaprHandler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaprHandler) ProtoMessage() {}

func (x *DaprHandler) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sdk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaprHandler.ProtoReflect.Descriptor instead.
func (*DaprHandler) Descriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *DaprHandler) GetModuleKind() DaprModuleKind {
	if x != nil {
		return x.ModuleKind
	}
	return DaprModuleKind_DaprModuleKindUnknown
}

func (x *DaprHandler) GetPkgPath() string {
	if x != nil {
		return x.PkgPath
	}
	return ""
}

func (x *DaprHandler) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *DaprHandler) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DaprHandler) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *DaprHandler) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *DaprHandler) GetComments() []string {
	if x != nil {
		return x.Comments
	}
	return nil
}

type UpdateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`           // 应用名
	Handlers      []*DaprHandler         `protobuf:"bytes,2,rep,name=handlers,proto3" json:"handlers,omitempty"` // AST解析后保存的Dapr处理函数列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteRequest) Reset() {
	*x = UpdateRouteRequest{}
	mi := &file_proto_sdk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteRequest) ProtoMessage() {}

func (x *UpdateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sdk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteRequest.ProtoReflect.Descriptor instead.
func (*UpdateRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_sdk_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRouteRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *UpdateRouteRequest) GetHandlers() []*DaprHandler {
	if x != nil {
		return x.Handlers
	}
	return nil
}

var File_proto_sdk_proto protoreflect.FileDescriptor

const file_proto_sdk_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/sdk.proto\x12\bprotobuf\"-\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\";\n" +
	"\tListParam\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\"\xc9\x02\n" +
	"\vDaprHandler\x128\n" +
	"\n" +
	"moduleKind\x18\x01 \x01(\x0e2\x18.protobuf.DaprModuleKindR\n" +
	"moduleKind\x12\x18\n" +
	"\apkgPath\x18\x02 \x01(\tR\apkgPath\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x05 \x01(\tR\x05alias\x12H\n" +
	"\vannotations\x18\a \x03(\v2&.protobuf.DaprHandler.AnnotationsEntryR\vannotations\x12\x1a\n" +
	"\bcomments\x18\x06 \x03(\tR\bcomments\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x12UpdateRouteRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x121\n" +
	"\bhandlers\x18\x02 \x03(\v2\x15.protobuf.DaprHandlerR\bhandlers*\x9a\x01\n" +
	"\x0eDaprModuleKind\x12\x19\n" +
	"\x15DaprModuleKindUnknown\x10\x00\x12\x1c\n" +
	"\x18DaprModuleKindInvocation\x10\x01\x12\x17\n" +
	"\x13DaprModuleKindEvent\x10\x02\x12\x1c\n" +
	"\x18DaprModuleKindDelayEvent\x10\x03\x12\x18\n" +
	"\x14DaprModuleKindHealth\x10\x04B\"Z github.com/hdget/sdk/common/protobufb\x06proto3"

var (
	file_proto_sdk_proto_rawDescOnce sync.Once
	file_proto_sdk_proto_rawDescData []byte
)

func file_proto_sdk_proto_rawDescGZIP() []byte {
	file_proto_sdk_proto_rawDescOnce.Do(func() {
		file_proto_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sdk_proto_rawDesc), len(file_proto_sdk_proto_rawDesc)))
	})
	return file_proto_sdk_proto_rawDescData
}

var file_proto_sdk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_sdk_proto_goTypes = []any{
	(DaprModuleKind)(0),        // 0: protobuf.DaprModuleKind
	(*Error)(nil),              // 1: protobuf.Error
	(*ListParam)(nil),          // 2: protobuf.ListParam
	(*DaprHandler)(nil),        // 3: protobuf.DaprHandler
	(*UpdateRouteRequest)(nil), // 4: protobuf.UpdateRouteRequest
	nil,                        // 5: protobuf.DaprHandler.AnnotationsEntry
}
var file_proto_sdk_proto_depIdxs = []int32{
	0, // 0: protobuf.DaprHandler.moduleKind:type_name -> protobuf.DaprModuleKind
	5, // 1: protobuf.DaprHandler.annotations:type_name -> protobuf.DaprHandler.AnnotationsEntry
	3, // 2: protobuf.UpdateRouteRequest.handlers:type_name -> protobuf.DaprHandler
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sdk_proto_init() }
func file_proto_sdk_proto_init() {
	if File_proto_sdk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sdk_proto_rawDesc), len(file_proto_sdk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sdk_proto_goTypes,
		DependencyIndexes: file_proto_sdk_proto_depIdxs,
		EnumInfos:         file_proto_sdk_proto_enumTypes,
		MessageInfos:      file_proto_sdk_proto_msgTypes,
	}.Build()
	File_proto_sdk_proto = out.File
	file_proto_sdk_proto_goTypes = nil
	file_proto_sdk_proto_depIdxs = nil
}
